### ISSUE TITLE
Header and footer positioning

### ISSUE THREAD

**Issue by AntoineBecquet** [ayann/active_admin_flat_skin#1]
The header size does not match depending on the screen's size.
Maybe try something like this:

```scss
.header#header {
  height: calc(100% - 52px);
}
```
