### ISSUE TITLE
Sidebar is not scrollable

### ISSUE THREAD

**Issue by bakku** [ayann/active_admin_flat_skin#9]
Hi!
We have more models than fit to the sidebar of the interface. But the sidebar is not scrollable so we can't reach these entries of the navigation.
Any ideas how to solve this?

**Comment by Martin288** [comment]
@bakku I added the below lines of codes and solved the problem.
```scss
#filters_sidebar_section {
  max-height: 80%;
  overflow-y: scroll;
}
```
